### ISSUE TITLE
Argomento numerico

### ISSUE THREAD

**Issue by valerio-bozzolan** [diegmonti/labs-tools-incolabot#1]
Ciao! :)

Volevo solo segnalare che quando nel `{{Bar7/Segnaladisc}}` si usa un argomento numerico:

https://it.wikipedia.org/w/index.php?title=Wikipedia:Bar/2017_08_4&diff=prev&oldid=89768621

Probabilmente lo scaper dovrebbe stripparlo via per evitare questo:

https://it.wikipedia.org/w/index.php?title=Template:Bar3/titoli/0&oldid=89768714

In ogni caso è fantastico che quando si sposta il titolo della pagina il bot effettua la correzione da solo :D

**Comment by diegmonti** [comment]
Ciao!

Grazie per la segnalazione. Sistemato con https://github.com/diegmonti/labs-tools-incolabot/commit/ea2a18814c629c5c9e81db1d8b010d2accce70f5.
